name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report! Please provide as much context as possible so we can fix the issue quickly.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug you encountered
      placeholder: "A clear and concise description of what the bug is..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: "The expected outcome..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the behavior
      value: |
        1.
        2.
        3.
      placeholder: "Step-by-step instructions..."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Tell us about your environment
      value: |
        - **Python version:** (e.g., 3.10, 3.11)
        - **OS:** (e.g., macOS, Linux, Windows)
        - **uv version:** (run `uv --version`)
        - **Project version:**
      placeholder: "Provide relevant environment details..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output (optional)
      render: python
      placeholder: "Paste error messages or traceback here..."

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues
          required: true
        - label: I have provided steps to reproduce the bug
          required: true
        - label: I am using the latest version
