name: Question / Discussion
description: Ask a question or start a discussion
title: "[Q&A]: "
labels: ["question", "discussion"]
type: feature_request
body:
  - type: markdown
    attributes:
      value: |
        Welcome! Feel free to ask questions or discuss topics related to this project.

  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What would you like to know?
      placeholder: "Ask your question clearly and concisely..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide relevant context to help us understand your question
      placeholder: "What are you trying to do? What have you already tried?"
    validations:
      required: true

  - type: input
    id: search
    attributes:
      label: Search terms used
      description: What did you search for before asking?
      placeholder: "e.g., 'how to customize uv', 'python 3.10 support'"

  - type: textarea
    id: references
    attributes:
      label: Relevant links or references
      description: Any documentation, issues, or external references? (optional)
      placeholder: |
        - Related issue: #123
        - Documentation: [link]
        - Similar discussion: [link]

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing discussions and issues
          required: true
        - label: I have provided context for my question
          required: true
